"""
Django settings for AZLive project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path: Path) -> None:
    """Load KEY=VALUE pairs from .env (does not override existing env vars)."""
    if not path.is_file():
        return
    for line in path.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        key, value = key.strip(), value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in '"\'':
            value = value[1:-1]
        if key not in os.environ or not os.environ[key]:
            os.environ[key] = value


# En test, on ne charge pas le .env local : les tests doivent être hermétiques et
# indépendants des secrets du développeur (Facebook/TikTok, app secret, etc.).
# Les tests qui ont besoin d'une configuration l'injectent via override_settings.
if 'test' not in sys.argv:
    _load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5q3tnh8b$92n8^-abr4icuzsp3ato^6n=k7)0oit3uz&i5+22+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    "corsheaders",
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'backend.apps.BackendConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'AZLive.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AZLive.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'AZLive'),
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
            # Réutilise la connexion PostgreSQL entre requêtes (au lieu d'en ouvrir
            # une nouvelle à chaque appel) : gain notable de latence en prod, surtout
            # avec le polling fréquent (lives/commandes) du frontend.
            'CONN_MAX_AGE': int(os.environ.get('POSTGRES_CONN_MAX_AGE', '60')),
            'CONN_HEALTH_CHECKS': True,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    # W1 — Sécurité par défaut : lecture publique, écriture authentifiée
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    # W2 — Pagination par défaut sur toutes les listes
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

CORS_ALLOW_ALL_ORIGINS = True

# Facebook OAuth / Graph API
FACEBOOK_APP_ID = os.environ.get('FACEBOOK_APP_ID', '')
FACEBOOK_APP_SECRET = os.environ.get('FACEBOOK_APP_SECRET', '')
FACEBOOK_REDIRECT_URI = os.environ.get(
    'FACEBOOK_REDIRECT_URI',
    'http://localhost:8000/api/auth/facebook/callback/',
)
FACEBOOK_LOGIN_SUCCESS_URL = os.environ.get(
    'FACEBOOK_LOGIN_SUCCESS_URL',
    'http://localhost:3000/auth/facebook/success',
)
FACEBOOK_OAUTH_SCOPES = os.environ.get(
    'FACEBOOK_OAUTH_SCOPES',
    'email,public_profile,pages_show_list,pages_read_engagement,pages_manage_metadata,pages_manage_posts,pages_messaging',
)
# Facebook Login for Business (app de type Entreprise) : ID de configuration.
# Si défini, l'URL OAuth utilise config_id au lieu de scope.
FACEBOOK_CONFIG_ID = os.environ.get('FACEBOOK_CONFIG_ID', '')
FACEBOOK_LIVE_STATUS = os.environ.get('FACEBOOK_LIVE_STATUS', 'LIVE_NOW')
FACEBOOK_WEBHOOK_VERIFY_TOKEN = os.environ.get(
    'FACEBOOK_WEBHOOK_VERIFY_TOKEN',
    'azlive_secure_webhook_token_2026',
)
FACEBOOK_WEBHOOK_FIELDS = os.environ.get(
    'FACEBOOK_WEBHOOK_FIELDS',
    'feed,messages',
)
# Timeout / retries des appels Graph API (commentaires live, OAuth, etc.).
# Augmenter FACEBOOK_GRAPH_TIMEOUT si le réseau est lent (SSL handshake timeout).
FACEBOOK_GRAPH_TIMEOUT = int(os.environ.get('FACEBOOK_GRAPH_TIMEOUT', '45'))
FACEBOOK_GRAPH_RETRIES = int(os.environ.get('FACEBOOK_GRAPH_RETRIES', '3'))

# URL publique de l'API (liens facture / étiquette dans les messages privés)
AZLIVE_PUBLIC_BASE_URL = os.environ.get('AZLIVE_PUBLIC_BASE_URL', 'http://localhost:8000')

# --- Compréhension des commentaires par LLM (repli du regex) ---
# Désactivé par défaut : sans clé/URL, le pipeline reste 100% regex (gratuit, hermétique).
# API compatible OpenAI (chat completions). Exemples GRATUITS :
#   - Groq free tier : BASE_URL=https://api.groq.com/openai/v1, MODEL=llama-3.3-70b-versatile
#   - Ollama local   : BASE_URL=http://localhost:11434/v1, MODEL=llama3.1 (API_KEY non requise)
AZLIVE_LLM_ENABLED = os.environ.get('AZLIVE_LLM_ENABLED', 'false').lower() in ('1', 'true', 'yes', 'on')
AZLIVE_LLM_BASE_URL = os.environ.get('AZLIVE_LLM_BASE_URL', '')
AZLIVE_LLM_API_KEY = os.environ.get('AZLIVE_LLM_API_KEY', '')
AZLIVE_LLM_MODEL = os.environ.get('AZLIVE_LLM_MODEL', '')
AZLIVE_LLM_TIMEOUT = int(os.environ.get('AZLIVE_LLM_TIMEOUT', '12'))

# File d'attente JP : relances + expiration automatique du client en tête.
# Délai (minutes) sans nouvelle d'un client ÉLIGIBLE (en tête de file) avant une relance.
AZLIVE_JP_RELANCE_DELAY_MINUTES = int(os.environ.get('AZLIVE_JP_RELANCE_DELAY_MINUTES', '30'))
# Nombre maximum de relances avant expiration.
AZLIVE_JP_MAX_RELANCES = int(os.environ.get('AZLIVE_JP_MAX_RELANCES', '3'))
# Thread daemon au boot Django (plus besoin de cron). false = désactiver.
AZLIVE_JP_RELANCE_AUTO = os.environ.get('AZLIVE_JP_RELANCE_AUTO', 'true').lower() in (
    '1', 'true', 'yes', 'on',
)
# Fréquence de passage du planificateur (secondes). Le délai réel reste DELAY_MINUTES.
AZLIVE_JP_RELANCE_POLL_SECONDS = int(os.environ.get('AZLIVE_JP_RELANCE_POLL_SECONDS', '60'))

# Reprise après annulation : réutiliser les infos de la dernière commande annulée
# seulement si elle date de moins de N heures (évite des données vieilles de semaines/mois).
AZLIVE_REPRISE_INFO_MAX_HOURS = int(os.environ.get('AZLIVE_REPRISE_INFO_MAX_HOURS', '72'))

# MediaMTX — pont WebRTC (navigateur) -> RTMPS (Facebook Live).
# Si MEDIAMTX_ENABLED est faux, le démarrage de live garde l'ancien comportement
# (l'URL RTMP est seulement renvoyée, à utiliser dans OBS).
MEDIAMTX_ENABLED = os.environ.get('MEDIAMTX_ENABLED', 'false').lower() in ('1', 'true', 'yes', 'on')
# API de contrôle de MediaMTX (provisioning des paths). Vue depuis Django.
MEDIAMTX_API_URL = os.environ.get('MEDIAMTX_API_URL', 'http://localhost:9997')
# URL WHIP donnée au navigateur.
# Sur Railway : laisse l'URL publique Django (proxy /api/media/whip/) car le
# domaine public MediaMTX renvoie souvent 502. En local : http://localhost:8889
MEDIAMTX_WHIP_BASE_URL = os.environ.get('MEDIAMTX_WHIP_BASE_URL', 'http://localhost:8889')
# Force le navigateur à passer par Django même si MEDIAMTX_WHIP_BASE_URL pointe ailleurs.
MEDIAMTX_WHIP_VIA_DJANGO = os.environ.get('MEDIAMTX_WHIP_VIA_DJANGO', 'true').lower() in (
    '1', 'true', 'yes', 'on',
)
# Base WHIP interne (private networking), joignable uniquement depuis Django.
# Ex. http://azlivemtxn.railway.internal:8189  (= port WHIP/$PORT des logs MediaMTX)
MEDIAMTX_WHIP_INTERNAL_BASE = os.environ.get('MEDIAMTX_WHIP_INTERNAL_BASE', '')
# Si INTERNAL_BASE vide : dérivé de MEDIAMTX_API_URL en remplaçant le port par celui-ci.
# Sur Railway : mets le $PORT WHIP des logs MediaMTX (ex. 8189).
MEDIAMTX_WEBRTC_PORT = os.environ.get('MEDIAMTX_WEBRTC_PORT', '8189')
# Hôte RTSP que ffmpeg (dans le conteneur MediaMTX) utilise pour relire le flux.
# En prod Railway : 127.0.0.1:8554 (ffmpeg et MediaMTX sont dans le même container).
MEDIAMTX_RTSP_HOST = os.environ.get('MEDIAMTX_RTSP_HOST', '127.0.0.1:8554')
# Paramètres d'encodage ffmpeg pour le relais vers Facebook (H.264 + AAC requis).
MEDIAMTX_FFMPEG_VIDEO_BITRATE = os.environ.get('MEDIAMTX_FFMPEG_VIDEO_BITRATE', '3000k')
MEDIAMTX_FFMPEG_PRESET = os.environ.get('MEDIAMTX_FFMPEG_PRESET', 'veryfast')

# TikTok OAuth (Login Kit) — Sandbox ou Production
TIKTOK_CLIENT_KEY = os.environ.get('TIKTOK_CLIENT_KEY', '')
TIKTOK_CLIENT_SECRET = os.environ.get('TIKTOK_CLIENT_SECRET', '')
TIKTOK_REDIRECT_URI = os.environ.get(
    'TIKTOK_REDIRECT_URI',
    'http://localhost:8000/api/auth/facebook/callback/',
)
TIKTOK_LOGIN_SUCCESS_URL = os.environ.get(
    'TIKTOK_LOGIN_SUCCESS_URL',
    'http://localhost:3000/auth/tiktok/success',
)
TIKTOK_OAUTH_SCOPES = os.environ.get('TIKTOK_OAUTH_SCOPES', 'user.info.basic')

# OAuth client public — réutilise TIKTOK_REDIRECT_URI (un seul callback à enregistrer chez TikTok)
TIKTOK_PUBLIC_REDIRECT_URI = os.environ.get(
    'TIKTOK_PUBLIC_REDIRECT_URI',
    TIKTOK_REDIRECT_URI,
)
TIKTOK_PUBLIC_OAUTH_SCOPES = os.environ.get(
    'TIKTOK_PUBLIC_OAUTH_SCOPES',
    'user.info.basic,user.info.profile',
)
# URL du frontend où rediriger le client après connexion TikTok
AZLIVE_PUBLIC_ORDER_BASE_URL = os.environ.get(
    'AZLIVE_PUBLIC_ORDER_BASE_URL',
    'http://localhost:3000',
)

# TikTools — commentaires live TikTok en temps réel
TIKTOOL_API_KEY = os.environ.get('TIKTOOL_API_KEY', '')
# Cookies session TikTok du compte streamer (sessionid + tt-target-idc) pour répondre dans le chat live
TIKTOK_SESSION_COOKIES = os.environ.get('TIKTOK_SESSION_COOKIES', '')

_extra_hosts = os.environ.get('DJANGO_EXTRA_ALLOWED_HOSTS', '')
if _extra_hosts:
    ALLOWED_HOSTS = ['*'] if ALLOWED_HOSTS == ['*'] else ALLOWED_HOSTS + [
        host.strip() for host in _extra_hosts.split(',') if host.strip()
    ]
