"""
Django settings for AZLive project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path: Path) -> None:
    """Load KEY=VALUE pairs from .env (does not override existing env vars)."""
    if not path.is_file():
        return
    for line in path.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        key, value = key.strip(), value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in '"\'':
            value = value[1:-1]
        if key not in os.environ or not os.environ[key]:
            os.environ[key] = value


# En test, on ne charge pas le .env local : les tests doivent être hermétiques et
# indépendants des secrets du développeur (Facebook/TikTok, app secret, etc.).
# Les tests qui ont besoin d'une configuration l'injectent via override_settings.
if 'test' not in sys.argv:
    _load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En production (Railway), définir DJANGO_SECRET_KEY. En local, la valeur par défaut suffit.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-5q3tnh8b$92n8^-abr4icuzsp3ato^6n=k7)0oit3uz&i5+22+',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Local: True par défaut. Prod: poser DJANGO_DEBUG=False.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')

ALLOWED_HOSTS = ['*']

# Derrière le proxy HTTPS de Railway/Netlify : reconnaître le schéma d'origine.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    "corsheaders",
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'backend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise sert les fichiers statiques (admin, DRF) en production.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'AZLive.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AZLive.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
else:
    # Prod (Supabase) : si DATABASE_URL est défini, il a priorité.
    # Ex: postgresql://postgres:<pwd>@<host>:5432/postgres
    _database_url = os.environ.get('DATABASE_URL')
    if _database_url:
        import dj_database_url

        DATABASES = {
            'default': dj_database_url.parse(
                _database_url,
                conn_max_age=600,
                ssl_require=True,
            )
        }
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.environ.get('POSTGRES_DB', 'AZLive'),
                'USER': os.environ.get('POSTGRES_USER', 'postgres'),
                'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
                'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
                'PORT': os.environ.get('POSTGRES_PORT', '5432'),
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    # W1 — Sécurité par défaut : lecture publique, écriture authentifiée
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    # W2 — Pagination par défaut sur toutes les listes
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

CORS_ALLOW_ALL_ORIGINS = True

# Origines de confiance pour le CSRF (admin/session) en prod, ex :
# CSRF_TRUSTED_ORIGINS=https://mon-back.up.railway.app,https://mon-site.netlify.app
_csrf_trusted = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_trusted.split(',') if o.strip()]

# Facebook OAuth / Graph API
FACEBOOK_APP_ID = os.environ.get('FACEBOOK_APP_ID', '')
FACEBOOK_APP_SECRET = os.environ.get('FACEBOOK_APP_SECRET', '')
FACEBOOK_REDIRECT_URI = os.environ.get(
    'FACEBOOK_REDIRECT_URI',
    'http://localhost:8000/api/auth/facebook/callback/',
)
FACEBOOK_LOGIN_SUCCESS_URL = os.environ.get(
    'FACEBOOK_LOGIN_SUCCESS_URL',
    'http://localhost:3000/auth/facebook/success',
)
FACEBOOK_OAUTH_SCOPES = os.environ.get(
    'FACEBOOK_OAUTH_SCOPES',
    'email,public_profile,pages_show_list,pages_read_engagement,pages_manage_metadata,pages_manage_posts,pages_messaging',
)
# Facebook Login for Business (app de type Entreprise) : ID de configuration.
# Si défini, l'URL OAuth utilise config_id au lieu de scope.
FACEBOOK_CONFIG_ID = os.environ.get('FACEBOOK_CONFIG_ID', '')
FACEBOOK_LIVE_STATUS = os.environ.get('FACEBOOK_LIVE_STATUS', 'LIVE_NOW')
FACEBOOK_WEBHOOK_VERIFY_TOKEN = os.environ.get(
    'FACEBOOK_WEBHOOK_VERIFY_TOKEN',
    'azlive_secure_webhook_token_2026',
)
FACEBOOK_WEBHOOK_FIELDS = os.environ.get(
    'FACEBOOK_WEBHOOK_FIELDS',
    'feed,messages',
)

# URL publique de l'API (liens facture / étiquette dans les messages privés)
AZLIVE_PUBLIC_BASE_URL = os.environ.get('AZLIVE_PUBLIC_BASE_URL', 'http://localhost:8000')

# File d'attente JP : relances + expiration automatique du client en tête.
# Délai (minutes) sans nouvelle d'un client ÉLIGIBLE (en tête de file) avant une relance.
AZLIVE_JP_RELANCE_DELAY_MINUTES = int(os.environ.get('AZLIVE_JP_RELANCE_DELAY_MINUTES', '30'))
# Nombre maximum de relances avant expiration.
AZLIVE_JP_MAX_RELANCES = int(os.environ.get('AZLIVE_JP_MAX_RELANCES', '3'))

# MediaMTX — pont WebRTC (navigateur) -> RTMPS (Facebook Live).
# Si MEDIAMTX_ENABLED est faux, le démarrage de live garde l'ancien comportement
# (l'URL RTMP est seulement renvoyée, à utiliser dans OBS).
MEDIAMTX_ENABLED = os.environ.get('MEDIAMTX_ENABLED', 'false').lower() in ('1', 'true', 'yes', 'on')
# API de contrôle de MediaMTX (provisioning des paths). Vue depuis Django.
MEDIAMTX_API_URL = os.environ.get('MEDIAMTX_API_URL', 'http://localhost:9997')
# URL WHIP de base donnée au navigateur (doit être joignable par le client, en HTTPS en prod).
MEDIAMTX_WHIP_BASE_URL = os.environ.get('MEDIAMTX_WHIP_BASE_URL', 'http://localhost:8889')
# Hôte RTSP que ffmpeg (dans MediaMTX) utilise pour relire le flux publié.
MEDIAMTX_RTSP_HOST = os.environ.get('MEDIAMTX_RTSP_HOST', 'localhost:8554')
# Paramètres d'encodage ffmpeg pour le relais vers Facebook (H.264 + AAC requis).
MEDIAMTX_FFMPEG_VIDEO_BITRATE = os.environ.get('MEDIAMTX_FFMPEG_VIDEO_BITRATE', '3000k')
MEDIAMTX_FFMPEG_PRESET = os.environ.get('MEDIAMTX_FFMPEG_PRESET', 'veryfast')

# TikTok OAuth (Login Kit) — Sandbox ou Production
TIKTOK_CLIENT_KEY = os.environ.get('TIKTOK_CLIENT_KEY', '')
TIKTOK_CLIENT_SECRET = os.environ.get('TIKTOK_CLIENT_SECRET', '')
TIKTOK_REDIRECT_URI = os.environ.get(
    'TIKTOK_REDIRECT_URI',
    'http://localhost:8000/api/auth/facebook/callback/',
)
TIKTOK_LOGIN_SUCCESS_URL = os.environ.get(
    'TIKTOK_LOGIN_SUCCESS_URL',
    'http://localhost:3000/auth/tiktok/success',
)
TIKTOK_OAUTH_SCOPES = os.environ.get('TIKTOK_OAUTH_SCOPES', 'user.info.basic')

# TikTools — commentaires live TikTok en temps réel
TIKTOOL_API_KEY = os.environ.get('TIKTOOL_API_KEY', '')

_extra_hosts = os.environ.get('DJANGO_EXTRA_ALLOWED_HOSTS', '')
if _extra_hosts:
    ALLOWED_HOSTS = ['*'] if ALLOWED_HOSTS == ['*'] else ALLOWED_HOSTS + [
        host.strip() for host in _extra_hosts.split(',') if host.strip()
    ]
