# Generated by Django 5.2.14 on 2026-05-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='localisation_actuelle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='livraison',
            name='tracking_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
