# Generated by Django 5.2.14 on 2026-06-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_client_social_handle_produit_code_jp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='produits_dressing',
            field=models.ManyToManyField(blank=True, related_name='lives_dressing', to='backend.produit'),
        ),
    ]
