# Generated by Django 5.2.14 on 2026-06-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_live_produits_dressing'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='pages_facebook',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
