# Generated by Django 5.2.14 on 2026-06-15 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_live_pages_facebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresPlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_commission', models.DecimalField(decimal_places=4, default=0.1, help_text='Taux de commission prélevé par la plateforme (ex: 0.10 = 10%)', max_digits=5)),
                ('nom_plateforme', models.CharField(default='AZLive', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres Plateforme',
                'verbose_name_plural': 'Paramètres Plateforme',
            },
        ),
        migrations.CreateModel(
            name='PageFacebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('pret', 'Prêt !'), ('inactif', 'Inactif')], default='pret', max_length=20)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages_facebook', to='backend.vendeur')),
            ],
            options={
                'unique_together': {('vendeur', 'page_id')},
            },
        ),
    ]
