# Generated by Django 5.2.14 on 2026-06-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_parametresplateforme_pagefacebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
