# Generated by Django 5.2.9 on 2026-06-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_client_heure_livraison_preferee'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
