# Generated by Django 5.2.9 on 2026-06-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_commande_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='quantite',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
