# Generated by Django 5.2.9 on 2026-06-25 08:25

import re

import django.db.models.deletion
from django.db import migrations, models


_JP_PREFIX_RE = re.compile(r'^(?:\s*JP[\s\-_]*)+', re.IGNORECASE)


def _normalize_code(raw):
    if raw is None:
        return ''
    code = str(raw).strip()
    stripped = _JP_PREFIX_RE.sub('', code)
    code = stripped if stripped else code
    return re.sub(r'\s+', ' ', code).strip().upper()


def strip_jp_prefix_and_seed_live_codes(apps, schema_editor):
    """Codes nus + seed des correspondances par live depuis produits_dressing."""
    Variante = apps.get_model('backend', 'Variante')
    Live = apps.get_model('backend', 'Live')
    LiveCodeJP = apps.get_model('backend', 'LiveCodeJP')

    # 1) Codes catalogue nus (sans prefixe « JP »).
    for variante in Variante.objects.all():
        bare = _normalize_code(variante.code_jp)
        if bare != (variante.code_jp or ''):
            variante.code_jp = bare
            variante.save(update_fields=['code_jp'])

    # 2) Une correspondance code -> variante par live, unique dans le live.
    for live in Live.objects.all():
        used_codes = set()
        for produit in live.produits_dressing.all():
            for variante in produit.variantes.all():
                base = _normalize_code(variante.code_jp)
                if not base:
                    continue
                code = base
                suffix = 1
                while code in used_codes:
                    suffix += 1
                    code = f'{base}-{suffix}'
                used_codes.add(code)
                LiveCodeJP.objects.get_or_create(
                    live=live, variante=variante, defaults={'code': code}
                )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_commande_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variante',
            name='code_jp',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='LiveCodeJP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_jp', to='backend.live')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_live', to='backend.variante')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('live', 'code'), name='unique_code_per_live'), models.UniqueConstraint(fields=('live', 'variante'), name='unique_variante_per_live')],
            },
        ),
        migrations.RunPython(strip_jp_prefix_and_seed_live_codes, noop_reverse),
    ]
