# Generated by Django 6.0.6 on 2026-07-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_variante_code_jp_livecodejp'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='turn_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametresplateforme',
            name='jp_turn_timeout_minutes',
            field=models.PositiveIntegerField(default=5, help_text="Timeout (minutes) pour confirmer une commande TikTok quand c'est son tour. Passé ce délai, le JP expire et le suivant passe."),
        ),
    ]
